on:
  workflow_dispatch:

jobs:
  issue-create-label:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ 'PAT', 'GHAPP', 'GHTOKEN']
    steps:
      - if: matrix.type == 'GHAPP'
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - env:
          TOKEN: ${{ steps.app-token.outputs.token || matrix.type == 'PAT' && secrets.PAT || github.token }}
        run: |
          curl -X POST \
          -H "Authorization: token $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d "{
            \"title\": \"Label Bug from ${{ matrix.type }}\",
            \"body\": \"Demonstrates the Label Bug\",
            \"assignees\": [\"anthms\"],
            \"milestone\": 1,
            \"labels\": [\"ktest:test-22029\"]
          }"
